language: java

# changes what code runs remotely on the server
script: mvn test -B

# sets operating system of virtual machine
os:
  - linux
  - osx

branches:
  only:
    - master

deploy:
  provider: heroku:git
  username:
    secure: